services:
  app:
    container_name: sloctavi-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Live bind mount
      - /app/node_modules # Prevent node_modules overwrite
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: ["pnpm", "dev"]

  db:
    image: postgres:15
    container_name: sloctavi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sloctavi
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: sloctavi-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
